version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Australia/Adelaide
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.3.23
    - 1.4.0
    - 1.4.1
    - 1.4.10
    - 1.4.2
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: lark-parser
    versions:
    - 0.11.1
